name: Close stale issues and PRs
on:
  schedule:
    - cron: '23 5 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          any-of-labels: 'needs-more-info,needs-demo'
